export const a = "Hello, \"world!\"";
export const b = "\x41 \x42 \x43"; // "A B C"
export const c = "foo\tbar";
export const d = "foo\nbar";
export const e = "foo\rbar";
export const f = "foo\\bar";
export const g = "foo\'bar";
export const h = "foo\"bar";
export const i = "foo\u{1F600}bar";
export const j = "foo \u0061 bar";
